name: anonia_chat_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.11.0
  google_sign_in: 5.2.3
  firebase_auth: ^3.3.5
  lottie: 1.2.1
  introduction_screen: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/loadingsplash/
  uses-material-design: true

